name: WcSync CI

on:
  push:
    branches: [ "master" ]
    paths:
      - WcSync/**
      - .github/workflows/build-wcsync.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: wcsync:latest

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Login
      uses: docker/login-action@v2.1.0
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: .
        file: WcSync/Dockerfile
        push: true
        tags: ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGE_NAME }}
